### PR TITLE
fix(protocol-kit): fixed `isL1SafeSingleton` issues and added the `replicate-address` playground

### LINKED ISSUE #929: [Docs]Example how to deploy to same address in different chains.
## Context / issue

Some developers would like to deploy the same Safe address into different chains when using the SDK. While this is possible is not the default behavior of the SDK, and it's also not clear that the SDK is able to manage this situation too.

## Proposed solution

Create an example showing how to get the same Safe address in different chains when using the SDK, and explain the different configuration parameters.

 - Create a playground showing this specific example
 - Update the docs to explain the parameters that help to get this behavior.
 - Create an example in devex section?

### PR DESCRIPTION
**Pull request by DaniSomoza**
## What it solves
Resolves #929

Some developers would like to deploy the same Safe address into different chains when using the SDK. While this is possible is not the default behavior of the SDK, and it's also not clear that the SDK is able to manage this situation too.

## How this PR fixes it

- Created a `replicate-address` playground showing this specific example.
- Fixed a bug in the `Safe.getAddress()` method (added `isL1SafeSingleton` param to `predictSafeAddress`)
- if a custom `deploymentType` is set and the address is not present in `safe-deployments` we throw an error in the `BaseContract`.
- Fix issue in `createSafeDeploymentTransaction` (added `deploymentType` param)

### Test

I used the `generate-safe-address`playground to get a Safe address starting with `0x5afe...` pattern:

- Safe Address:  `0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3`
- Safe Owners: `[ '0x0Ee26C4481485AC64BfFf2bdCaA21EdAeCEcdCa9' ]`
- Safe Threshold: `1`
- Safe version: `v1.3.0`
- Deployment addresses: `cannonical`
- `L2` Contact used

Safe saltNonce:  `1124214`

I used the `replicate-address` playground to deploy this Safe in different chains

- `Gnosis chain`: [`0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3`](https://gnosisscan.io/address/0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3)
- `Polygon`: [`0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3`](https://polygonscan.com/address/0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3)
- `Sepolia`: [`0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3`](https://sepolia.etherscan.io/address/0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3)
- `Chaindo chain`: [`0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3`](https://gnosis-chiado.blockscout.com/address/0x5afe088ACE21Ce244c950d9c7A026C6c9Af953e3?tab=contract)

### `replicate-address` playground

Captura de pantalla 2024-10-14 a las 10 21 56

### CODE REVIEW

File: packages/protocol-kit/src/types/safeProvider.ts [hunk 1]
```diff
@@ -43,7 +43,7 @@ export type PasskeyClient = Client<
   WalletActions<Chain | undefined, Account> & PasskeyActions
 >
 
-export type ExternalSigner = WalletClient<Transport, Chain | undefined, Account> | PasskeyClient
+export type ExternalSigner = WalletClient<Transport, Chain | undefined, Account>
```
Comment (dasanra) [inline packages/protocol-kit/src/types/safeProvider.ts:46]: Why did you change this type?

https://github.com/safe-global/safe-core-sdk/blob/dc98509f15f42f04d65edcbada3bcf1f61f1154a/packages/protocol-kit/src/SafeProvider.ts#L172

**Review by dasanra — APPROVED** [review]
