### PR TITLE
fix(api-kit): add missing properties to types

### LINKED ISSUE #1064: SafeMultisigTransactionResponse dataDecoded field's type
## Description

Hi there,

I’ve recently started using the safe-sdk and came across what seems to be a type mismatch. When using the `getMultisigTransactions` method from SafeApiKit (imported from @safe-global/api-kit) on an instance of new SafeApiKit, the API returns structured data for the `dataDecoded` field. However, the `SafeMultisigTransactionResponse` type, which is the return type of the `getMultisigTransactions` method, defines `dataDecoded as a string` as seen [here](https://github.com/safe-global/safe-core-sdk/blob/014f365e46cf278897c5ece45c1490c7c749f2d7/packages/types-kit/src/types.ts#L234).

Could you confirm if this is expected behavior or if the type definition needs to be updated?

Thanks for your help!

What I do is very simple:

```typescript

const getTransactionList = async () => {
    const safeApiClient = new SafeApiKit({ chainId }) // I put the instance creation here for simplicity of having the relevant line of codes
    const trxList = await safeApiClient.getMultisigTransactions(
      process.env.NEXT_PUBLIC_SAFE_WALLET_ADDRESS
    )
    
   return trxList
}
```

What it returns:

Screenshot 2024-12-02 at 18 59 32

## Environment
- Safe Core SDK versions:
  
  - api-kit: `2.5.4`
  - protocol-kit: `5.0.4`
  - relay-kit: `3.2.4`
  - types-kit: `1.0.0`
  - sdk-starter-kit:
- Safe contract version: `1.4.1+L2`
- Environment:
  - browser: chrome

## Expected result

The field of `decodedData` [here](https://github.com/safe-global/safe-core-sdk/blob/014f365e46cf278897c5ece45c1490c7c749f2d7/packages/types-kit/src/types.ts#L234) respects the return type of the api field.

## Additional context

I'm using the sdk in a nextjs project.

### PR DESCRIPTION
**Pull request by dasanra**
## What it solves
Resolves #1064, #1085, #1088

## How this PR fixes it
Adds missing properties to types

### CODE REVIEW

File: packages/api-kit/src/SafeApiKit.ts [hunk 1]
```diff
@@ -258,6 +258,14 @@ class SafeApiKit {
     return sendRequest({
       url: `${this.#txServiceBaseUrl}/v1/safes/${address}/`,
       method: HttpMethod.Get
+    }).then((response: any) => {
+      // FIXME remove when service returns the singleton property
```
Comment (DaniSomoza) [inline packages/api-kit/src/SafeApiKit.ts:262]:
```suggestion
      // FIXME remove when the service always returns the singleton property
```

I Think that this small change makes clear that the condition for removal is when the API always consistently returns the singleton property.

**Review by DaniSomoza — APPROVED** [review]
