### PR TITLE
fix(protocol-kit): safeDeploymentConfig is an optional parameter in PredictedSafeProps

### LINKED ISSUE #426: safeDeploymentConfig property is mandatory
## Description

safeDeploymentConfig object is mandatory when initializing the safeSDK predicting the Safe address but all it's properties are optional. If you don't want to set any of the properties you still need to set an empty object.

## Environment

- Package: protocol-kit
- Package version: 1.0.0

## Expected result
Is not necessary to set an empty object if no need to set any of the properties

## More context
https://github.com/safe-global/safe-core-sdk/blob/f2e8e82d88d815d7b278f605a125f4cfb2816020/packages/protocol-kit/src/types/index.ts#L22-L29

### PR DESCRIPTION
**Pull request by DaniSomoza**
## What it solves
Resolves #426

## How this PR fixes it

`safeDeploymentConfig` is an optional parameter in the `PredictSafeProps` type

```
export interface PredictedSafeProps {
  safeAccountConfig: SafeAccountConfig
  safeDeploymentConfig?: SafeDeploymentConfig
}
```

### CODE REVIEW

File: packages/protocol-kit/src/contracts/utils.ts [hunk 1]
```diff
@@ -23,7 +23,7 @@ export const PREDETERMINED_SALT_NONCE =
 export interface PredictSafeProps {
```
Comment (germartinez) [inline packages/protocol-kit/src/contracts/utils.ts:23]: Renaming this type would help to differentiate it more from `PredictedSafeProps`. Also the name of the funciton is `predictedSafeAddress()`, so I think it makes sense.
```suggestion
export interface PredictSafeAddressProps {
```

File: packages/protocol-kit/tests/e2e/utilsContracts.test.ts [hunk 2]
```diff
@@ -453,5 +454,41 @@ describe('Contract utils', () => {
       chai.expect(secondPredictedSafeAddress).to.be.equal(expectedSafeAddress)
       chai.expect(thirdPredictedSafeAddress).to.be.equal(expectedSafeAddress)
     })
+
+    itif(safeVersionDeployed > '1.0.0')(
```
Comment (germartinez) [inline packages/protocol-kit/tests/e2e/utilsContracts.test.ts:458]: Beautiful test. Just checking this check is done because in case `safeDeploymentConfig` is not passed, the default version will be (currently) `v1.3.0` and its use would break with the `v1.0.0` contracts deployed by Hardhat when using `customContracts` variable

Comment (germartinez) [reply packages/protocol-kit/tests/e2e/utilsContracts.test.ts:458]: when calling `setup` method in the contract, because of the number or parameters of the function

Comment (germartinez) [reply packages/protocol-kit/tests/e2e/utilsContracts.test.ts:458]: Okay, what I was thinking. All good then!

File: packages/protocol-kit/src/contracts/utils.ts (hunk 1 above)
Comment (DaniSomoza) [reply packages/protocol-kit/src/contracts/utils.ts]: done!

**Review by germartinez — APPROVED** [review]
